name: world_picker
description: Country selector and metadata provider with flags, currency, and more.
version: 0.0.1

homepage: https://github.com/williamsimionatto/world_picker
repository: https://github.com/williamsimionatto/world_picker
issue_tracker: https://github.com/williamsimionatto/world_picker/issues
documentation: https://github.com/williamsimionatto/world_picker#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  assets:
    - assets/flags/
