name: world_picker
description: Country selector and metadata provider with flags, currency, and more.
version: 0.1.1+5

homepage: https://github.com/williamsimionatto/world_picker
repository: https://github.com/williamsimionatto/world_picker
issue_tracker: https://github.com/williamsimionatto/world_picker/issues
documentation: https://github.com/williamsimionatto/world_picker#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  phone_numbers_parser: ^9.0.3

flutter:
  assets:
    - assets/flags/
